site_name: DataSanta
site_url: https://datasatanism.com
site_dir: web
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.footer
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      authors_file: "{blog}/.authors.yml"
      categories_allowed:
        - Mathematics
        - Programming
        - Numerical Methods
        - Data Science
        - Machine Learning
        - Classification
        - Computational Methods
        - Dimensionality Reduction
        - Feature Engineering
        - Data Visualization
        - Linear Algebra
        - Data Transformations
        - Deep Learning
        - Speech and Audio Processing
        - Natural Language Processing
        - TTS (Text to Speech)
        - Neural Networks
        - Loss Functions
      pagination_per_page: 5
  - tags:
      tags_file: .tags.md
  - search
  - social
  - glightbox
  - rss:
      match_path: "posts/.*"
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
nav:
  - index.md
  - about.md
extra:
  social:
  - icon: /fontawesome/regular/envelope
    name: send me an email
    link: mailto:contact@datasatanism.com
  - icon: fontawesome/brands/youtube
    name: YouTube
    link: https://www.youtube.com/@datasatanism
  - icon: fontawesome/brands/github
    name: GitHub
    link: https://github.com/nickovchinnikov
  - icon: fontawesome/brands/x-twitter
    name: DataSanta on X
    link: https://x.com/datasatanisma
  - icon: fontawesome/brands/facebook
    name: DataSatanism on Facebook
    link: https://www.facebook.com/groups/datasatanisma
  - icon: fontawesome/brands/reddit-alien
    name: Reddit Sub
    link: https://www.reddit.com/r/datasatanism/
  - icon: fontawesome/brands/telegram
    name: DataSatanism on telegram
    link: https://t.me/datasatanisma
  - icon: fontawesome/solid/rss
    name: RSS Feed
    link: /feed_rss_created.xml
  analytics:
    provider: google
    property: G-YQ1VTYK2L7
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.details
extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
