name: Deploy blog to GitHub Pages
on:
  push:
    branches:
      - master  # or whatever your default branch is
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Configure Git Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Adjust if you need a specific version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs-material
        pip install "mkdocs-material[imaging]"
        pip install cairocffi cairosvg
        pip install mkdocs-glightbox
        pip install mkdocs-rss-plugin

    - name: Build and Deploy MkDocs
      run: mkdocs gh-deploy --force
